<?php
include('getSession.php');

$title           = $_POST['name'];
$description     = $_POST['description'];
$website         = $_POST['website'];

// properly handle characters to avoid sql injection
$title       = addslashes($title); 
$description = addslashes($description); 
$website     = addslashes($website); 

$temp_page_id = 'temp_id';
$query = "INSERT INTO `initiative` (`id`, `creator_id`, `rank`  ,`upvotes`, `downvotes`, `netvotes`, `ishidden`, `title`, `description`, `page_id`     , `www`, `creation_time`) VALUES (NULL, '$USER_ID'  , '1'       ,'0'        , '0'          ,  '0'        ,     '0'     ,  '$title',  '$description' , '$temp_page_id' , '$website',  $CURRENT_TIME )";

$addToTable = mysqli_query($dbc,$query) or die ("Error in query: $query " . mysqli_error($dbc));
$InitiativeID = mysqli_insert_id($dbc);
$page_id = "initiative_". $InitiativeID . ".php"; 

$query = "UPDATE `initiative` SET `page_id` = '$page_id' WHERE `id` = '$InitiativeID'";
$updateInitiative = mysqli_query($dbc,$query) or die ("Error in query: $query " . mysqli_error($dbc));


// CREATE PAGE
$newInitiativePage = fopen($page_id, "w");
$initiativeString =  "$" . "INITIATIVE_ID = " . $InitiativeID .";\n";
fwrite($newInitiativePage, "<?php\n");
fwrite($newInitiativePage, "// THIS PAGE WAS AUTOGENERATED UPON INITIATIVE CREATION.\n");
fwrite($newInitiativePage, "include('getSession.php');\n");
fwrite($newInitiativePage, $initiativeString);
fwrite($newInitiativePage, "include('initiative_base.php');\n");
fwrite($newInitiativePage, "?>\n");
fclose($newInitiativePage);

echo '<script>window.location.href="' . $page_id. '";</script>';

?>